import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1784820834266 implements MigrationInterface {
    name = 'InitSchema1784820834266'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "asset_categories" ("category_id" SERIAL NOT NULL, "category_name" character varying NOT NULL, "asset_type" character varying, "parent_category_id" integer, CONSTRAINT "PK_b2cb3a25440804bc3081ffb2762" PRIMARY KEY ("category_id")); COMMENT ON COLUMN "asset_categories"."asset_type" IS 'hardware / license / vehicle / tool / furniture ... single source of truth ของ type (ไม่ซ้ำกับ assets แล้ว)'`);
        await queryRunner.query(`CREATE TABLE "vendors" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "vendor_id" SERIAL NOT NULL, "vendor_name" character varying NOT NULL, "vendor_type" character varying, "contact_info" character varying, CONSTRAINT "PK_0a594d3003be38ea23c2fce9a3c" PRIMARY KEY ("vendor_id")); COMMENT ON COLUMN "vendors"."vendor_type" IS 'ผู้ขาย / ผู้รับซ่อม / บริษัทประกัน'`);
        await queryRunner.query(`CREATE TABLE "permissions" ("permission_id" SERIAL NOT NULL, "permission_code" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_f65dbbe5dc253ff51e8a1f894df" UNIQUE ("permission_code"), CONSTRAINT "PK_1717db2235a5b169822e7f753b1" PRIMARY KEY ("permission_id")); COMMENT ON COLUMN "permissions"."permission_code" IS 'requisition.create / requisition.view_own / requisition.view_all / requisition.approve / asset.view / asset.create / asset.update / asset.delete'`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("role_id" SERIAL NOT NULL, "role_name" character varying NOT NULL, "description" character varying, CONSTRAINT "PK_09f4c8130b54f35925588a37b6a" PRIMARY KEY ("role_id")); COMMENT ON COLUMN "roles"."role_name" IS 'employee / admin — ขยาย role ใหม่ได้ในอนาคต'`);
        await queryRunner.query(`CREATE TABLE "employee_roles" ("employee_id" integer NOT NULL, "role_id" integer NOT NULL, "assigned_date" date, CONSTRAINT "PK_8bf7f2fbc9039751cd34d9f9606" PRIMARY KEY ("employee_id", "role_id"))`);
        await queryRunner.query(`CREATE TABLE "employees" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "employee_id" SERIAL NOT NULL, "employee_code" character varying NOT NULL, "full_name" character varying NOT NULL, "department_id" integer, "position" character varying, "email" character varying, "phone" character varying, CONSTRAINT "UQ_56162b5f24af743a154680684f5" UNIQUE ("employee_code"), CONSTRAINT "PK_c9a09b8e6588fb4d3c9051c8937" PRIMARY KEY ("employee_id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "department_id" SERIAL NOT NULL, "company_id" integer, "department_name" character varying NOT NULL, "site" character varying, "parent_department_id" integer, CONSTRAINT "PK_202cd845b076ed15836884084eb" PRIMARY KEY ("department_id")); COMMENT ON COLUMN "departments"."site" IS 'office / factory1 / factory2'`);
        await queryRunner.query(`CREATE TABLE "companies" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "company_id" SERIAL NOT NULL, "company_code" character varying NOT NULL, "company_name" character varying NOT NULL, CONSTRAINT "UQ_c59133f1df5217119eedb39754c" UNIQUE ("company_code"), CONSTRAINT "PK_8c008cd5c4c0c20cf1e77f68e8d" PRIMARY KEY ("company_id"))`);
        await queryRunner.query(`CREATE TABLE "locations" ("location_id" SERIAL NOT NULL, "company_id" integer, "location_name" character varying NOT NULL, "location_type" character varying, "site" character varying, "parent_location_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_582bb9b1865f02814bd7c2c9650" PRIMARY KEY ("location_id")); COMMENT ON COLUMN "locations"."location_type" IS 'คลัง / office / factory / ห้องเก็บของ'`);
        await queryRunner.query(`CREATE TYPE "public"."assets_current_status_enum" AS ENUM('in_stock', 'assigned', 'under_repair', 'in_transit', 'disposed', 'expired')`);
        await queryRunner.query(`CREATE TYPE "public"."assets_current_holder_type_enum" AS ENUM('employee', 'department', 'location', 'vendor')`);
        await queryRunner.query(`CREATE TABLE "assets" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "asset_id" SERIAL NOT NULL, "asset_no" character varying NOT NULL, "category_id" integer, "asset_name" character varying NOT NULL, "serial_number" character varying, "brand_model" character varying, "vendor_id" integer, "purchase_date" date, "purchase_cost" numeric(14,2), "warranty_expire_date" date, "current_status" "public"."assets_current_status_enum", "current_location_id" integer, "current_holder_type" "public"."assets_current_holder_type_enum", "current_holder_id" integer, "attributes" jsonb, "notes" text, "created_by" integer, CONSTRAINT "UQ_4cad3364e4d1a45a8f769b33a89" UNIQUE ("asset_no"), CONSTRAINT "PK_ba1dca7766f77b6c475091f860c" PRIMARY KEY ("asset_id")); COMMENT ON COLUMN "assets"."asset_no" IS 'เช่น FA-2026-00123'; COMMENT ON COLUMN "assets"."vendor_id" IS 'ผู้ขายตอนซื้อ'; COMMENT ON COLUMN "assets"."current_holder_id" IS 'polymorphic — ดู currentHolderType ประกอบเพื่อ resolve เป็น employee/department/location/vendor'; COMMENT ON COLUMN "assets"."attributes" IS 'เช่น license: {seats, license_key}'`);
        await queryRunner.query(`CREATE INDEX "IDX_bfdc3fe63eb7269f4a28625264" ON "assets" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9da03d06e2af9f607159e88426" ON "assets" ("serial_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb9344645830ebe2f78ee61e33" ON "assets" ("current_holder_id") `);
        await queryRunner.query(`CREATE TYPE "public"."warranties_status_enum" AS ENUM('active', 'expired', 'renewed')`);
        await queryRunner.query(`CREATE TABLE "warranties" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "warranty_id" SERIAL NOT NULL, "asset_id" integer NOT NULL, "vendor_id" integer, "start_date" date NOT NULL, "end_date" date NOT NULL, "status" "public"."warranties_status_enum" NOT NULL DEFAULT 'active', "coverage_detail" text, CONSTRAINT "PK_3c59ad4aaec7bb71efb00171152" PRIMARY KEY ("warranty_id")); COMMENT ON COLUMN "warranties"."vendor_id" IS 'บริษัทประกัน/ผู้รับประกัน'`);
        await queryRunner.query(`CREATE TABLE "users" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "user_id" SERIAL NOT NULL, "username" character varying NOT NULL, "email" character varying, "password_hash" character varying NOT NULL, "refresh_token_hash" text, "is_active" boolean NOT NULL DEFAULT true, "employee_id" integer, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_9760615d88ed518196bb79ea03d" UNIQUE ("employee_id"), CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "stock_items" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "stock_item_id" SERIAL NOT NULL, "category_id" integer, "item_name" character varying NOT NULL, "unit" character varying, "description" text, CONSTRAINT "PK_f79e338cd4bfeae9341703119c5" PRIMARY KEY ("stock_item_id")); COMMENT ON COLUMN "stock_items"."unit" IS 'หน่วยนับ เช่น ชิ้น / อัน / กล่อง / เส้น'`);
        await queryRunner.query(`CREATE TABLE "stock_levels" ("stock_level_id" SERIAL NOT NULL, "stock_item_id" integer NOT NULL, "location_id" integer NOT NULL, "quantity_on_hand" integer NOT NULL DEFAULT '0', "updated_at" TIMESTAMP, CONSTRAINT "PK_a106baf141b7fec68757445d023" PRIMARY KEY ("stock_level_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_92c5c16369f092b6169d5b753c" ON "stock_levels" ("stock_item_id", "location_id") `);
        await queryRunner.query(`CREATE TABLE "requisition_items" ("requisition_item_id" SERIAL NOT NULL, "requisition_id" integer NOT NULL, "asset_id" integer, "stock_item_id" integer, "quantity" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_00136233158e5d9df56c2edc642" PRIMARY KEY ("requisition_item_id")); COMMENT ON COLUMN "requisition_items"."asset_id" IS 'กรณีขอ serialized asset เฉพาะเครื่อง'; COMMENT ON COLUMN "requisition_items"."stock_item_id" IS 'กรณีขอของ consumable/bulk'; COMMENT ON COLUMN "requisition_items"."quantity" IS 'ใช้กับ stock_item เท่านั้น, asset ใช้ 1 เสมอ'`);
        await queryRunner.query(`CREATE TYPE "public"."requisition_approvals_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "requisition_approvals" ("approval_id" SERIAL NOT NULL, "requisition_id" integer NOT NULL, "approval_level" integer NOT NULL, "approver_id" integer NOT NULL, "status" "public"."requisition_approvals_status_enum" NOT NULL DEFAULT 'pending', "actioned_at" TIMESTAMP, "comment" text, CONSTRAINT "PK_b94927766cab454df4e2c94f823" PRIMARY KEY ("approval_id")); COMMENT ON COLUMN "requisition_approvals"."approval_level" IS 'ลำดับชั้นการอนุมัติ 1,2,3...'`);
        await queryRunner.query(`CREATE TYPE "public"."requisitions_request_type_enum" AS ENUM('withdraw', 'borrow')`);
        await queryRunner.query(`CREATE TYPE "public"."requisitions_overall_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "requisitions" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "requisition_id" SERIAL NOT NULL, "requisition_no" character varying NOT NULL, "requested_by" integer NOT NULL, "request_type" "public"."requisitions_request_type_enum" NOT NULL, "overall_status" "public"."requisitions_overall_status_enum" NOT NULL DEFAULT 'pending', "due_date" date, "reason" text, CONSTRAINT "UQ_549a6dcfa1cdace76725ccc9608" UNIQUE ("requisition_no"), CONSTRAINT "PK_53968828441803c91cfac24a9c3" PRIMARY KEY ("requisition_id")); COMMENT ON COLUMN "requisitions"."due_date" IS 'กำหนดคืน (เฉพาะ borrow)'`);
        await queryRunner.query(`CREATE TYPE "public"."repairs_status_enum" AS ENUM('reported', 'repairing', 'sent_to_vendor', 'repaired', 'closed')`);
        await queryRunner.query(`CREATE TYPE "public"."repairs_result_enum" AS ENUM('fixed', 'unrepairable', 'waiting_parts')`);
        await queryRunner.query(`CREATE TABLE "repairs" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "repair_id" SERIAL NOT NULL, "asset_id" integer NOT NULL, "reported_by" integer NOT NULL, "problem_description" text, "status" "public"."repairs_status_enum" NOT NULL DEFAULT 'reported', "vendor_id" integer, "sent_to_vendor_date" TIMESTAMP, "repaired_date" TIMESTAMP, "result" "public"."repairs_result_enum", "repair_cost" numeric(14,2), "notes" text, CONSTRAINT "PK_0783461396dac77410c46e59f6d" PRIMARY KEY ("repair_id")); COMMENT ON COLUMN "repairs"."vendor_id" IS 'ผู้รับซ่อม กรณีส่งซ่อมนอก'`);
        await queryRunner.query(`CREATE TABLE "purchase_order_items" ("po_item_id" SERIAL NOT NULL, "po_id" integer NOT NULL, "category_id" integer, "item_description" character varying NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(14,2), "received_quantity" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_7bb2812689e11702af0f8f3fdec" PRIMARY KEY ("po_item_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('draft', 'ordered', 'partially_received', 'received', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "po_id" SERIAL NOT NULL, "po_no" character varying NOT NULL, "vendor_id" integer, "order_date" date, "expected_delivery_date" date, "requested_by" integer, "approved_by" integer, "status" "public"."purchase_orders_status_enum" NOT NULL DEFAULT 'draft', "total_amount" numeric(14,2), CONSTRAINT "UQ_23692958c9d9f6bc2fd05c716e0" UNIQUE ("po_no"), CONSTRAINT "PK_75fd7d58e79d0c6c6acba7ff7a4" PRIMARY KEY ("po_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."movements_movement_type_enum" AS ENUM('received_to_stock', 'issued', 'returned', 'transferred_department', 'transferred_location', 'sent_to_repair', 'returned_from_repair', 'warranty_renewed', 'disposed')`);
        await queryRunner.query(`CREATE TYPE "public"."movements_from_holder_type_enum" AS ENUM('employee', 'department', 'location', 'vendor')`);
        await queryRunner.query(`CREATE TYPE "public"."movements_to_holder_type_enum" AS ENUM('employee', 'department', 'location', 'vendor')`);
        await queryRunner.query(`CREATE TABLE "movements" ("movement_id" SERIAL NOT NULL, "asset_id" integer NOT NULL, "movement_type" "public"."movements_movement_type_enum" NOT NULL, "from_location_id" integer, "to_location_id" integer, "from_holder_type" "public"."movements_from_holder_type_enum", "from_holder_id" integer, "to_holder_type" "public"."movements_to_holder_type_enum", "to_holder_id" integer, "reference_type" character varying, "reference_id" integer, "performed_by" integer NOT NULL, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_de3867a4eb45fd1dfa83cc67bb2" PRIMARY KEY ("movement_id")); COMMENT ON COLUMN "movements"."reference_type" IS 'assignment / repair / warranty / disposal / goods_receipt'; COMMENT ON COLUMN "movements"."reference_id" IS 'PK ของตารางต้นทางตาม reference_type'`);
        await queryRunner.query(`CREATE TABLE "goods_receipt_items" ("receipt_item_id" SERIAL NOT NULL, "receipt_id" integer NOT NULL, "po_item_id" integer, "asset_id" integer, "stock_item_id" integer, "received_quantity" integer, "condition_on_receipt" character varying, CONSTRAINT "CHK_505129e65e9a1a1f2cf1414bc1" CHECK (("asset_id" IS NOT NULL AND "stock_item_id" IS NULL) OR ("asset_id" IS NULL AND "stock_item_id" IS NOT NULL)), CONSTRAINT "PK_b1c3427eb7595e59549e891ae95" PRIMARY KEY ("receipt_item_id")); COMMENT ON COLUMN "goods_receipt_items"."asset_id" IS 'กรณี serialized asset — 1 แถวต่อ 1 ชิ้น'; COMMENT ON COLUMN "goods_receipt_items"."stock_item_id" IS 'กรณี consumable/bulk'; COMMENT ON COLUMN "goods_receipt_items"."received_quantity" IS 'ใช้กับ stock_item_id (bulk) เท่านั้น, serialized ใช้ 1 เสมอ'`);
        await queryRunner.query(`CREATE TABLE "goods_receipts" ("receipt_id" SERIAL NOT NULL, "receipt_no" character varying NOT NULL, "po_id" integer, "receipt_date" date, "received_by" integer, "location_id" integer, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bbc24348eda2c119f713e2e927f" UNIQUE ("receipt_no"), CONSTRAINT "PK_f8f0a0631d132ec5cdc70327f7e" PRIMARY KEY ("receipt_id")); COMMENT ON COLUMN "goods_receipts"."location_id" IS 'คลังที่รับเข้า'`);
        await queryRunner.query(`CREATE TYPE "public"."disposals_disposal_method_enum" AS ENUM('sold', 'donated', 'destroyed', 'written_off')`);
        await queryRunner.query(`CREATE TABLE "disposals" ("disposal_id" SERIAL NOT NULL, "asset_id" integer NOT NULL, "disposal_method" "public"."disposals_disposal_method_enum" NOT NULL, "disposal_date" date NOT NULL, "sale_amount" numeric(14,2), "approved_by" integer, "reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6979b7db3fd7db97d0e6b20ff14" UNIQUE ("asset_id"), CONSTRAINT "PK_896c2e2e0377a36caeaae7eed21" PRIMARY KEY ("disposal_id")); COMMENT ON COLUMN "disposals"."sale_amount" IS 'มูลค่าที่ขายได้ (ถ้ามี)'`);
        await queryRunner.query(`CREATE TABLE "attachments" ("attachment_id" SERIAL NOT NULL, "reference_type" character varying NOT NULL, "reference_id" integer NOT NULL, "file_name" character varying NOT NULL, "file_url" character varying NOT NULL, "mime_type" character varying, "file_size_bytes" bigint, "uploaded_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0f0c0f540cbf0f2e9499f9a082e" PRIMARY KEY ("attachment_id")); COMMENT ON COLUMN "attachments"."reference_type" IS 'asset / requisition / repair / goods_receipt / disposal ...'`);
        await queryRunner.query(`CREATE TYPE "public"."assignments_assignment_type_enum" AS ENUM('permanent', 'temporary_loan', 'replacement')`);
        await queryRunner.query(`CREATE TYPE "public"."assignments_holder_type_enum" AS ENUM('employee', 'department', 'location', 'vendor')`);
        await queryRunner.query(`CREATE TYPE "public"."assignments_return_condition_enum" AS ENUM('normal', 'damaged', 'lost')`);
        await queryRunner.query(`CREATE TABLE "assignments" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "assignment_id" SERIAL NOT NULL, "asset_id" integer NOT NULL, "requisition_id" integer, "assignment_type" "public"."assignments_assignment_type_enum" NOT NULL, "holder_type" "public"."assignments_holder_type_enum" NOT NULL, "holder_id" integer NOT NULL, "issued_date" TIMESTAMP NOT NULL, "issued_by" integer NOT NULL, "due_date" date, "returned_date" TIMESTAMP, "received_by" integer, "return_condition" "public"."assignments_return_condition_enum", "notes" text, CONSTRAINT "PK_d6c1d70f2bb5464c5b3a5269bb9" PRIMARY KEY ("assignment_id")); COMMENT ON COLUMN "assignments"."holder_id" IS 'polymorphic — ตาม holderType'; COMMENT ON COLUMN "assignments"."due_date" IS 'กำหนดคืน (borrow/temporary_loan)'`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD CONSTRAINT "FK_4e03f20770553682e801cff07d3" FOREIGN KEY ("parent_category_id") REFERENCES "asset_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("permission_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_roles" ADD CONSTRAINT "FK_04aafdf0252f05451916c4810ec" FOREIGN KEY ("employee_id") REFERENCES "employees"("employee_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_roles" ADD CONSTRAINT "FK_13f42debabcdc155b21632097cf" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_678a3540f843823784b0fe4a4f2" FOREIGN KEY ("department_id") REFERENCES "departments"("department_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_541e3d07c93baa9cc42b149a5fb" FOREIGN KEY ("company_id") REFERENCES "companies"("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_2d6673ae91cee09bef47d2a5de2" FOREIGN KEY ("parent_department_id") REFERENCES "departments"("department_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_4f97374ec57955950cf6ab13326" FOREIGN KEY ("company_id") REFERENCES "companies"("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_06f770dfdf4e78f67ad08f80cdc" FOREIGN KEY ("parent_location_id") REFERENCES "locations"("location_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_bfdc3fe63eb7269f4a286252641" FOREIGN KEY ("category_id") REFERENCES "asset_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_a4d58da8b1bdb73a0946964e6cc" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("vendor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_0772d6a84abca60a0001c5432b1" FOREIGN KEY ("current_location_id") REFERENCES "locations"("location_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_dccd1dbe2c036b9ab80876466b7" FOREIGN KEY ("created_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warranties" ADD CONSTRAINT "FK_27f3efc5d2da0557fcb8d4fad93" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warranties" ADD CONSTRAINT "FK_6d4947a25eaddfcd917ba0437db" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("vendor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_9760615d88ed518196bb79ea03d" FOREIGN KEY ("employee_id") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_items" ADD CONSTRAINT "FK_c342d1b8e90bb3af870ef991d21" FOREIGN KEY ("category_id") REFERENCES "asset_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_levels" ADD CONSTRAINT "FK_d169967e0b3af6d23bfeaa515db" FOREIGN KEY ("stock_item_id") REFERENCES "stock_items"("stock_item_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_levels" ADD CONSTRAINT "FK_ff889f98a5594dc3e6a244db354" FOREIGN KEY ("location_id") REFERENCES "locations"("location_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisition_items" ADD CONSTRAINT "FK_2afa61cf14fa20efa7dc12883dd" FOREIGN KEY ("requisition_id") REFERENCES "requisitions"("requisition_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisition_items" ADD CONSTRAINT "FK_1ad9b1e1b3a4752217893bf3767" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisition_items" ADD CONSTRAINT "FK_c2e32140af365a1d076568ebf78" FOREIGN KEY ("stock_item_id") REFERENCES "stock_items"("stock_item_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisition_approvals" ADD CONSTRAINT "FK_e6bc907f9c15d5ea7073237aadd" FOREIGN KEY ("requisition_id") REFERENCES "requisitions"("requisition_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisition_approvals" ADD CONSTRAINT "FK_50b5ef675fa051739ac07852936" FOREIGN KEY ("approver_id") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requisitions" ADD CONSTRAINT "FK_3f95cd2a896589d4feca828617f" FOREIGN KEY ("requested_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repairs" ADD CONSTRAINT "FK_141836252a436da35068d6b0073" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repairs" ADD CONSTRAINT "FK_b1b27ce8ad47c40d46ae83255d8" FOREIGN KEY ("reported_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repairs" ADD CONSTRAINT "FK_e84697661cdb38e1a90f7a80096" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("vendor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_a6404cc1ff12740ea768e6ea9c2" FOREIGN KEY ("po_id") REFERENCES "purchase_orders"("po_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_0e62442b491cf43d43435e4b7c9" FOREIGN KEY ("category_id") REFERENCES "asset_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_346ae76b48e8f5042cf93b8df26" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("vendor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_2b788037fbd86a9406baeb8c85a" FOREIGN KEY ("requested_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_396e7d9c9ddef24e5af83a23316" FOREIGN KEY ("approved_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movements" ADD CONSTRAINT "FK_b6305513da39fbac7f9058f7742" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movements" ADD CONSTRAINT "FK_99a7c197e65d6ed124fa245d2c8" FOREIGN KEY ("from_location_id") REFERENCES "locations"("location_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movements" ADD CONSTRAINT "FK_5c55b113a73242423ebf91c226f" FOREIGN KEY ("to_location_id") REFERENCES "locations"("location_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movements" ADD CONSTRAINT "FK_98fe8e7e00eeefaef85d36bb816" FOREIGN KEY ("performed_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_items" ADD CONSTRAINT "FK_fb46f28f13fb590b0d8470d32d7" FOREIGN KEY ("receipt_id") REFERENCES "goods_receipts"("receipt_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_items" ADD CONSTRAINT "FK_929daa02a2dd91b2a8fc9f60e8e" FOREIGN KEY ("po_item_id") REFERENCES "purchase_order_items"("po_item_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_items" ADD CONSTRAINT "FK_e1b7b501c2e977bf21231596293" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_items" ADD CONSTRAINT "FK_9e128ff12058ef6706661dcd5b7" FOREIGN KEY ("stock_item_id") REFERENCES "stock_items"("stock_item_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipts" ADD CONSTRAINT "FK_f03f68a6a9c40e2ff70c9399884" FOREIGN KEY ("po_id") REFERENCES "purchase_orders"("po_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipts" ADD CONSTRAINT "FK_4dc96f6157a0e7865ca1b72aaa5" FOREIGN KEY ("received_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goods_receipts" ADD CONSTRAINT "FK_62011da18e989cf38e580b43175" FOREIGN KEY ("location_id") REFERENCES "locations"("location_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disposals" ADD CONSTRAINT "FK_6979b7db3fd7db97d0e6b20ff14" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disposals" ADD CONSTRAINT "FK_701ec9bc4c273935660867aba3c" FOREIGN KEY ("approved_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58" FOREIGN KEY ("uploaded_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_f38629a3327e8b7033ca15a6a0c" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_9892f1e841def48764f949738bc" FOREIGN KEY ("requisition_id") REFERENCES "requisitions"("requisition_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_2bf1c3f533b13cc5b18564aad06" FOREIGN KEY ("issued_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_27bdaefb16c3279d3215265a355" FOREIGN KEY ("received_by") REFERENCES "employees"("employee_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_27bdaefb16c3279d3215265a355"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_2bf1c3f533b13cc5b18564aad06"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_9892f1e841def48764f949738bc"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_f38629a3327e8b7033ca15a6a0c"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58"`);
        await queryRunner.query(`ALTER TABLE "disposals" DROP CONSTRAINT "FK_701ec9bc4c273935660867aba3c"`);
        await queryRunner.query(`ALTER TABLE "disposals" DROP CONSTRAINT "FK_6979b7db3fd7db97d0e6b20ff14"`);
        await queryRunner.query(`ALTER TABLE "goods_receipts" DROP CONSTRAINT "FK_62011da18e989cf38e580b43175"`);
        await queryRunner.query(`ALTER TABLE "goods_receipts" DROP CONSTRAINT "FK_4dc96f6157a0e7865ca1b72aaa5"`);
        await queryRunner.query(`ALTER TABLE "goods_receipts" DROP CONSTRAINT "FK_f03f68a6a9c40e2ff70c9399884"`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_items" DROP CONSTRAINT "FK_9e128ff12058ef6706661dcd5b7"`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_items" DROP CONSTRAINT "FK_e1b7b501c2e977bf21231596293"`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_items" DROP CONSTRAINT "FK_929daa02a2dd91b2a8fc9f60e8e"`);
        await queryRunner.query(`ALTER TABLE "goods_receipt_items" DROP CONSTRAINT "FK_fb46f28f13fb590b0d8470d32d7"`);
        await queryRunner.query(`ALTER TABLE "movements" DROP CONSTRAINT "FK_98fe8e7e00eeefaef85d36bb816"`);
        await queryRunner.query(`ALTER TABLE "movements" DROP CONSTRAINT "FK_5c55b113a73242423ebf91c226f"`);
        await queryRunner.query(`ALTER TABLE "movements" DROP CONSTRAINT "FK_99a7c197e65d6ed124fa245d2c8"`);
        await queryRunner.query(`ALTER TABLE "movements" DROP CONSTRAINT "FK_b6305513da39fbac7f9058f7742"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_396e7d9c9ddef24e5af83a23316"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_2b788037fbd86a9406baeb8c85a"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_346ae76b48e8f5042cf93b8df26"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_0e62442b491cf43d43435e4b7c9"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_a6404cc1ff12740ea768e6ea9c2"`);
        await queryRunner.query(`ALTER TABLE "repairs" DROP CONSTRAINT "FK_e84697661cdb38e1a90f7a80096"`);
        await queryRunner.query(`ALTER TABLE "repairs" DROP CONSTRAINT "FK_b1b27ce8ad47c40d46ae83255d8"`);
        await queryRunner.query(`ALTER TABLE "repairs" DROP CONSTRAINT "FK_141836252a436da35068d6b0073"`);
        await queryRunner.query(`ALTER TABLE "requisitions" DROP CONSTRAINT "FK_3f95cd2a896589d4feca828617f"`);
        await queryRunner.query(`ALTER TABLE "requisition_approvals" DROP CONSTRAINT "FK_50b5ef675fa051739ac07852936"`);
        await queryRunner.query(`ALTER TABLE "requisition_approvals" DROP CONSTRAINT "FK_e6bc907f9c15d5ea7073237aadd"`);
        await queryRunner.query(`ALTER TABLE "requisition_items" DROP CONSTRAINT "FK_c2e32140af365a1d076568ebf78"`);
        await queryRunner.query(`ALTER TABLE "requisition_items" DROP CONSTRAINT "FK_1ad9b1e1b3a4752217893bf3767"`);
        await queryRunner.query(`ALTER TABLE "requisition_items" DROP CONSTRAINT "FK_2afa61cf14fa20efa7dc12883dd"`);
        await queryRunner.query(`ALTER TABLE "stock_levels" DROP CONSTRAINT "FK_ff889f98a5594dc3e6a244db354"`);
        await queryRunner.query(`ALTER TABLE "stock_levels" DROP CONSTRAINT "FK_d169967e0b3af6d23bfeaa515db"`);
        await queryRunner.query(`ALTER TABLE "stock_items" DROP CONSTRAINT "FK_c342d1b8e90bb3af870ef991d21"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_9760615d88ed518196bb79ea03d"`);
        await queryRunner.query(`ALTER TABLE "warranties" DROP CONSTRAINT "FK_6d4947a25eaddfcd917ba0437db"`);
        await queryRunner.query(`ALTER TABLE "warranties" DROP CONSTRAINT "FK_27f3efc5d2da0557fcb8d4fad93"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_dccd1dbe2c036b9ab80876466b7"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_0772d6a84abca60a0001c5432b1"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_a4d58da8b1bdb73a0946964e6cc"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_bfdc3fe63eb7269f4a286252641"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_06f770dfdf4e78f67ad08f80cdc"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_4f97374ec57955950cf6ab13326"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_2d6673ae91cee09bef47d2a5de2"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_541e3d07c93baa9cc42b149a5fb"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_678a3540f843823784b0fe4a4f2"`);
        await queryRunner.query(`ALTER TABLE "employee_roles" DROP CONSTRAINT "FK_13f42debabcdc155b21632097cf"`);
        await queryRunner.query(`ALTER TABLE "employee_roles" DROP CONSTRAINT "FK_04aafdf0252f05451916c4810ec"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP CONSTRAINT "FK_4e03f20770553682e801cff07d3"`);
        await queryRunner.query(`DROP TABLE "assignments"`);
        await queryRunner.query(`DROP TYPE "public"."assignments_return_condition_enum"`);
        await queryRunner.query(`DROP TYPE "public"."assignments_holder_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."assignments_assignment_type_enum"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP TABLE "disposals"`);
        await queryRunner.query(`DROP TYPE "public"."disposals_disposal_method_enum"`);
        await queryRunner.query(`DROP TABLE "goods_receipts"`);
        await queryRunner.query(`DROP TABLE "goods_receipt_items"`);
        await queryRunner.query(`DROP TABLE "movements"`);
        await queryRunner.query(`DROP TYPE "public"."movements_to_holder_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."movements_from_holder_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."movements_movement_type_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_order_items"`);
        await queryRunner.query(`DROP TABLE "repairs"`);
        await queryRunner.query(`DROP TYPE "public"."repairs_result_enum"`);
        await queryRunner.query(`DROP TYPE "public"."repairs_status_enum"`);
        await queryRunner.query(`DROP TABLE "requisitions"`);
        await queryRunner.query(`DROP TYPE "public"."requisitions_overall_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."requisitions_request_type_enum"`);
        await queryRunner.query(`DROP TABLE "requisition_approvals"`);
        await queryRunner.query(`DROP TYPE "public"."requisition_approvals_status_enum"`);
        await queryRunner.query(`DROP TABLE "requisition_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92c5c16369f092b6169d5b753c"`);
        await queryRunner.query(`DROP TABLE "stock_levels"`);
        await queryRunner.query(`DROP TABLE "stock_items"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "warranties"`);
        await queryRunner.query(`DROP TYPE "public"."warranties_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb9344645830ebe2f78ee61e33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9da03d06e2af9f607159e88426"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfdc3fe63eb7269f4a28625264"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TYPE "public"."assets_current_holder_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."assets_current_status_enum"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TABLE "employee_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "vendors"`);
        await queryRunner.query(`DROP TABLE "asset_categories"`);
    }

}
